services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf.dev:/etc/nginx/conf.d/default.conf
      - ./backend/backend/django-static:/django-static
      - ./backend/backend/api-media-sdn:/api-media-sdn
      - ./frontend/build:/frontend/build
      - ./frontend/assets:/frontend/assets
    depends_on:
      - daphne
    networks:
      - webnet


  redis:
    image: redis
    restart: always
    networks:
      - webnet
  

  daphne:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: daphne:v2
    command: bash -c "cd backend && daphne -b 0.0.0.0 -p 8771 core.asgi:application -v2"
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis
    volumes:
      - ./backend/backend/api-media-sdn:/backend/backend/api-media-sdn
    depends_on:
      - redis
      - db
    networks:
      - webnet

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  tgbot:
    build:
      context: ./tgbot
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    command: bash -c "python bot.py"
    depends_on:
      - daphne
      - db
    restart: always
    networks:
      - webnet

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "cd backend && celery -A core worker --loglevel=info"
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis
    depends_on:
      - daphne
      - redis
      - db
    networks:
      - webnet

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "cd backend && celery -A core beat --loglevel=info"
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis
    depends_on:
      - daphne
      - redis
      - db
    networks:
      - webnet

networks:
  webnet: