# Generated by Django 5.1.3 on 2024-11-16 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rehab',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор программы реабилитации', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Название программы реабилитации', max_length=30, null=True)),
                ('description', models.TextField(blank=True, help_text='Подробное описание программы реабилитации', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи')),
                ('end_date', models.DateTimeField(blank=True, help_text='Дата завершения программы реабилитации', null=True)),
                ('duration', models.PositiveIntegerField(blank=True, default=0, help_text='Продолжительность программы реабилитации в днях', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Стоимость программы реабилитации в валюте', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли программа реабилитации')),
                ('doctors', models.ManyToManyField(blank=True, help_text='Врачи, которые ведут программу реабилитации', related_name='doctor_programs', related_query_name='doctor_program', to='users.doctor', verbose_name='Врачи')),
                ('patient', models.ForeignKey(blank=True, default=None, help_text='Пациент, которому принадлежит программа реабилитации', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_programs', related_query_name='user_program', to='users.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Программа реабилитации',
                'verbose_name_plural': 'Программы реабилитации',
                'ordering': ['created_at'],
            },
        ),
    ]
