# Generated by Django 5.1.3 on 2024-11-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehab',
            name='name',
            field=models.CharField(blank=True, help_text='Название программы реабилитации', max_length=128, null=True),
        ),
    ]
