# Generated by Django 5.1.3 on 2024-11-17 03:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0002_alter_rehab_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehab',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Стоимость программы реабилитации в рублях', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PatientMeasure',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор показателя', primary_key=True, serialize=False)),
                ('measurement_type', models.CharField(help_text='Тип измеряемого показателя (например, температура, давление)', max_length=128)),
                ('value', models.FloatField(help_text='Значение показателя')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время записи показателя')),
                ('photo', models.ImageField(blank=True, help_text='Фотография показателя', null=True, upload_to='measurements/')),
                ('file', models.FileField(blank=True, help_text='Файл показателя', null=True, upload_to='measurements/')),
                ('patient', models.ForeignKey(help_text='Пациент, которому принадлежат показатели', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='users.patient')),
                ('rehab', models.ForeignKey(help_text='Программа реабилитации, к которой относится показатель', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='rehab.rehab')),
            ],
            options={
                'verbose_name': 'Показатель пациента',
                'verbose_name_plural': 'Показатели пациентов',
            },
        ),
        migrations.CreateModel(
            name='RehabMedication',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор лекарства', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название лекарства', max_length=128)),
                ('dosage', models.CharField(blank=True, help_text='Дозировка лекарства', max_length=128, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Инструкции по применению лекарства', null=True)),
                ('comment', models.TextField(blank=True, help_text='Комментарии к лекарству', null=True)),
                ('rehab', models.ForeignKey(help_text='Программа реабилитации, к которой относится лекарство', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='rehab.rehab')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
            },
        ),
        migrations.CreateModel(
            name='RehabMedicationRecord',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи о приеме лекарства', primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Дата приема лекарства')),
                ('taken', models.BooleanField(default=False, help_text='Принято ли лекарство')),
                ('medication', models.ForeignKey(help_text='Назначенное лекарство', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rehab.rehabmedication')),
            ],
            options={
                'verbose_name': 'Запись о приеме лекарства',
                'verbose_name_plural': 'Записи о приеме лекарств',
            },
        ),
    ]
