# Generated by Django 5.1.3 on 2024-11-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0003_alter_rehab_cost_patientmeasure_rehabmedication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabmedication',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Продолжительность применения лекарства в днях', null=True),
        ),
    ]
