# Generated by Django 5.1.3 on 2024-11-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0004_rehabmedication_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabmedication',
            name='times',
            field=models.JSONField(blank=True, default=list, help_text='Время приема лекарства', null=True),
        ),
    ]
