# Generated by Django 5.1.3 on 2024-11-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0006_rehabmedication_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabmedicationrecord',
            name='date',
            field=models.DateTimeField(help_text='Дата приема лекарства'),
        ),
    ]
