# Generated by Django 5.1.3 on 2024-11-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0007_alter_rehabmedicationrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabmedicationrecord',
            name='is_notify_tg',
            field=models.BooleanField(default=False, help_text='Отправлено ли уведомление о приеме лекарства'),
        ),
    ]
