# Generated by Django 5.1.3 on 2024-11-17 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0008_rehabmedicationrecord_is_notify_tg'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabmedication',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Дата начала применения лекарства', null=True),
        ),
    ]
