# Generated by Django 5.1.3 on 2024-11-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0009_rehabmedication_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmeasure',
            name='ai_data',
            field=models.JSONField(blank=True, help_text='Данные для распознавания показателя', null=True),
        ),
    ]
