# Generated by Django 5.1.3 on 2024-11-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0010_patientmeasure_ai_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmeasure',
            name='patient',
        ),
    ]
