# Generated by Django 5.1.3 on 2024-11-26 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0011_remove_patientmeasure_patient'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureDevice',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор устроиства', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название устроиства', max_length=128)),
                ('description', models.TextField(help_text='Описание устроиства')),
            ],
        ),
        migrations.CreateModel(
            name='RehabMedicationTemplate',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор шаблона лекарства', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название лекарства', max_length=128)),
                ('dosage', models.CharField(blank=True, help_text='Дозировка лекарства', max_length=128, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Продолжительность применения лекарства в днях', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Инструкции по применению лекарства', null=True)),
                ('times', models.JSONField(blank=True, default=list, help_text='Время приема лекарства', null=True)),
                ('comment', models.TextField(blank=True, help_text='Комментарии к лекарству', null=True)),
                ('periodicity', models.CharField(choices=[('daily', 'Каждый день'), ('weekly', 'Каждую неделю'), ('monthly', 'Каждый месяц')], default='daily', help_text='Периодичность приема лекарства', max_length=10)),
            ],
            options={
                'verbose_name': 'Шаблон лекарства',
                'verbose_name_plural': 'Шаблоны лекарств',
            },
        ),
        migrations.RemoveField(
            model_name='patientmeasure',
            name='ai_data',
        ),
        migrations.RemoveField(
            model_name='patientmeasure',
            name='file',
        ),
        migrations.RemoveField(
            model_name='patientmeasure',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='patientmeasure',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='patientmeasure',
            name='value',
        ),
        migrations.CreateModel(
            name='PatientDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(help_text='Устройство', on_delete=django.db.models.deletion.CASCADE, related_name='patient_devices', to='rehab.measuredevice')),
                ('patient', models.ForeignKey(help_text='Пациент', on_delete=django.db.models.deletion.CASCADE, related_name='patient_devices', to='users.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patientmeasure',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Устройство', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='rehab.patientdevice'),
        ),
        migrations.CreateModel(
            name='PatientMeasureRecord',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи о показателе', primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время записи показателя')),
                ('value', models.CharField(blank=True, help_text='Значение показателя', max_length=128, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Фотография показателя', null=True, upload_to='measurements/')),
                ('file', models.FileField(blank=True, help_text='Файл показателя', null=True, upload_to='measurements/')),
                ('ai_data', models.JSONField(blank=True, default=dict, help_text='Данные для распознавания показателя', null=True)),
                ('is_crytical', models.BooleanField(default=False, help_text='Критический ли показатель')),
                ('patient_comment', models.TextField(blank=True, help_text='Комментарии к показателю', null=True)),
                ('ai_comment', models.TextField(blank=True, help_text='Комментарии к распознаванию показателя', null=True)),
                ('patient_measure', models.ForeignKey(help_text='Показатель', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='rehab.patientmeasure')),
            ],
            options={
                'verbose_name': 'Запись о показателе пациента',
                'verbose_name_plural': 'Записи о показателях пациентов',
            },
        ),
    ]
