# Generated by Django 5.1.3 on 2024-11-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0012_measuredevice_rehabmedicationtemplate_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measuredevice',
            options={'verbose_name': 'Устроиство', 'verbose_name_plural': 'Устроиства'},
        ),
        migrations.AlterModelOptions(
            name='patientdevice',
            options={'verbose_name': 'Устройство пациента', 'verbose_name_plural': 'Устройства пациентов'},
        ),
        migrations.CreateModel(
            name='DangerousMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Сообщение')),
                ('dateTime', models.DateTimeField(auto_now_add=True, help_text='Дата и время')),
                ('readed', models.BooleanField(default=False, help_text='Прочитано ли')),
                ('measure', models.ForeignKey(blank=True, help_text='Показатель', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dangerous_measures', to='rehab.patientmeasure')),
                ('patien', models.ForeignKey(help_text='Пациент', on_delete=django.db.models.deletion.CASCADE, related_name='dangerous_measures', to='users.patient')),
            ],
            options={
                'verbose_name': 'Опасный показатель',
                'verbose_name_plural': 'Опасные показатели',
            },
        ),
    ]
