# Generated by Django 5.1.3 on 2024-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0013_alter_measuredevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredevice',
            name='ai_settings',
            field=models.JSONField(default=dict, help_text='Настройки для распознавания'),
        ),
        migrations.AddField(
            model_name='measuredevice',
            name='settings',
            field=models.JSONField(default=dict, help_text='Настройки устроиства'),
        ),
    ]
