# Generated by Django 5.1.3 on 2024-11-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0014_measuredevice_ai_settings_measuredevice_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredevice',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фотография устроиства', null=True, upload_to='devices/'),
        ),
    ]
