# Generated by Django 5.1.3 on 2024-11-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0015_measuredevice_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredevice',
            name='inventory_number',
            field=models.CharField(blank=True, help_text='Инвентарный номер устроиства', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='measuredevice',
            name='ai_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Настройки для распознавания', null=True),
        ),
        migrations.AlterField(
            model_name='measuredevice',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Настройки устроиства', null=True),
        ),
    ]
