# Generated by Django 5.1.3 on 2024-11-27 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0016_measuredevice_inventory_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangerousmeasure',
            name='measure',
            field=models.ForeignKey(blank=True, help_text='Показатель', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dangerous_measures', to='rehab.patientmeasurerecord'),
        ),
    ]
